### ISSUE TITLE
[Bug]: Vocation

### ISSUE THREAD

**Issue by dex-89** [opentibiabr/otservbr-global#2696]
### What happened?

https://www.youtube.com/watch?v=6Qn-DVRfdus

### How to Reproduce?

1. Log in
2. Press CTRL+G or log out

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SaiyansKing** [comment]
The problem is that this repository still use old vocation client ids for promoted vocations so client thinks you lost your promotion after login.
The promotion is indicated by adding "10" to the non-promoted vocation client id.
Example: https://github.com/Erza/optimized_forgottenserver/blob/master/data/XML/vocations.xml#L53
