### ISSUE TITLE
[Bug]: The Explorer Society Quest

### ISSUE THREAD

**Issue by JohnleoRM** [opentibiabr/otservbr-global#358]
### What happened?

The key 3801 in the chest is bugged, and the NPC Uzgod dont response for the word "brooch"

### How to Reproduce?

key 3801 
20:12 You see a chest.
It weighs 120.00 oz.
Item ID: 1740, Unique ID: 5004
Client ID: 2472
Position: 32648, 31905, 3

20:14 You see Uzgod.
Health: 100 / 100.
Position: 32664, 31895, 9

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
I was doing this quest with friends today, I'll explain more detail on what's happening:
Emperor cookie quest: gives wrong key (instead of 3801 we got bugged key 0100)
Explorer society joining quest: wrong value is assigned to player storage for main Explorer society variable - resulting in wrong progress and also Uzgod not accepting Dwarven pickaxe (condition about main explorer quest storage variable equal to 2 is not met)
