### ISSUE TITLE
[problem] heavy backpack drag in dead body 

### ISSUE THREAD

**Issue by Slec** [opentibiabr/otservbr-global#370]
### What happened?

The anti-heavy backpack drag system is annoying itself, but when a player dies without blessing you just cant take main backpack back, you have to drag all backpacks inside it out.
Thus players cant bagloot our put supplies on hunts entrance anymore, since they cant drag heavy backpack

### How to Reproduce?

1 - die without blessing
2 - try to get your heavy bacpack back

Supply bag / lootbag
1 - try to drag heavy backpack

### Version

12.x (Default)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nyedson** [comment]
I think this check and impossibility of moving the backpack is because the players managed to bring down the server by moving a heavy backpack quickly using a program.

But if you think this is getting in the way and it's not necessary, go to data/events/scripts/players.lua, in line 1:
CONTAINER_WEIGHT_CHECK = true -- true = enable / false = disable
just put false iinstead of true or in line 2:
CONTAINER_WEIGHT_MAX = 1000000 -- 1000000 = 10k = 10000.00 oz
increase the max weight

**Comment by Slec** [comment]
I mean, i can garantee you players are going to leave your server soon with this feature, it really hurts the gameplay and i presume the point of this engine is to be actually usefull? 
So maybe if u cqn actually crash the server by dragging with a program its smart to add a cooldown for dragging instead cancel the drag?
I dont wanna think its not necessary and open a possibipity to crash my server, i want good solutions.
