### ISSUE TITLE
[Bug]: Diamond arrow spell + arrow usage

### ISSUE THREAD

**Issue by joelslamospersson** [opentibiabr/otservbr-global#410]
### What happened?

Diamond arrows does not have an AoE and they don't deplete.

### How to Reproduce?

Just discovered those things, currently no answer

### Relevant log output

```shell
None
```

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcosvf132** [comment]
There are **two** 'diamond arrows' registered on the server and on the client. Both have the same **name** and **sprite** but one arrow **decay and vanish** (From old paladin spell) and the other one is just like another **regular arrow** that you can but from any ammo NPC. The old 'diamond arrow' indeed does not have AoE effect since it's not beeing used anymore, to use the right 'diamond arrow' with AoE effect you must buy it from any ammo NPC or do a '/i' on it. **The same goes to 'spectral bolt!**
![image](https://user-images.githubusercontent.com/66353315/152896434-8641cff4-355a-47c9-ab09-6fb595ff982f.png)

- Tested on compat-release v1.1.0
