### ISSUE TITLE
[Bug]:  Not working Quest doors and locked doors that had a action id to be unlocked 

### ISSUE THREAD

**Issue by lafegob** [opentibiabr/otservbr-global#509]
### What happened?

All locked doors that you should be able to unlock with a specific key that has a action id are not working.
Once i click use on the key and use it on the door it's not unlocking :( 
Also the quest doors  ( not the level doors) are not working properly.

### How to Reproduce?

just run the last build provided here and you will see it.

### Relevant log output

```shell
i didn't got any error log on the console related to it
```

### Attach any relevant file

x

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mattyx14** [comment]
For the key to work you must assign an actionID equal to the key

Similarly, in the map editor, the door that you must place is the one with the locked attribute.

![image](https://user-images.githubusercontent.com/2807739/158686717-1fa61361-4e0e-42f9-aa3c-45fcef4d8bef.png)

**Comment by lafegob** [comment]
> For the key to work you must assign an actionID equal to the key
> 
> Similarly, in the map editor, the door that you must place is the one with the locked attribute.
> 
> ![image](https://user-images.githubusercontent.com/2807739/158686717-1fa61361-4e0e-42f9-aa3c-45fcef4d8bef.png)

Greetings Matt,

Thanks for replying Sir. 

Yep i'm aware about the action ID.
And it's not working, for example, if you look for the action 5010 ( black knight quest) 
I can see that the door has the proper actionid associated with it on map.
But it''s still not working :( 

That's why i was saying to check it..

And this is happening also to the quest doors ( not that necessary will be the same issue) 
but for both doors types it's not working. :(

Thanks in advance guys for this great community work.

**Comment by lucascebertin** [comment]
I can confirm that behaviour... the key looks correct, the door action id looks correct and still the door doesnt unlocks.
The output for the client is "You cannot use this object".

![image](https://user-images.githubusercontent.com/6990857/161965837-fb2ab6ca-b374-4b2f-96b4-64a528550eb8.png)
![image](https://user-images.githubusercontent.com/6990857/161965886-181ad4b0-b5b6-42f4-9e14-4e79d55b0b2a.png)

Following the message through the code, this message is stored in this `RETURNVALUE_CANNOTUSETHISOBJECT` and there are several places being referenced.
Well, because it's a "use" with a player item or something like this could be this `Game::playerUseItem` function in `game.cpp` and I see this particular line, looks a little bit weird but I can't say for sure.

```cpp
	Item* item = thing->getItem();
	if (!item || item->isUseable() || item->getClientID() != spriteId) { // look, when item->isUseable is true, that message can be returned to the client. 
		player->sendCancelMessage(RETURNVALUE_CANNOTUSETHISOBJECT);
		return;
	}
```

Other similar places have a `!` right before this check, see `Game::playerUseItemEx`:
```cpp
	Item* item = thing->getItem();
	if (!item || !item->isUseable() || item->getClientID() != fromSpriteId) {
		player->sendCancelMessage(RETURNVALUE_CANNOTUSETHISOBJECT);
		return;
	}
```

I'm not sure about this but someone else probably can confirm or not.

**Comment by lucascebertin** [comment]
Sorry, my bad, just tested and this works as intended.
A call to `Actions::useItemEx` happens and then this path is executed:
```cpp
  if (!action->executeUse(
          player, item, fromPos,
          action->getTarget(player, creature, toPos, toStackPos), toPos,
          isHotkey)) {
    if (!action->hasOwnErrorHandler()) {
      player->sendCancelMessage(RETURNVALUE_CANNOTUSETHISOBJECT);
    }
    return false;
```

Don't know why yet...

**Comment by lucascebertin** [comment]
Alright, `data/lib/tables/door.lua` have a variable called `keysID` and there is missing this 2969 (silver key).
```lua
-- ID of the keys. (2969 is from the thieves guild quest)
keysID = {2967, 2968, 2969, 2970, 2971, 2972, 2973, 21392}
```

I've just ignored this comment before the keysID and now that door finally can be unlocked.
Again, @victorperin solved the puzzle.

**Comment by andersonfaaria** [comment]
solved in https://github.com/opentibiabr/otservbr-global/pull/525
