### ISSUE TITLE
[Bug]: Emperor's Cookies Quest - wrong key delivered

### ISSUE THREAD

**Issue by sircurse** [opentibiabr/otservbr-global#528]
### What happened?

When getting the second key that should be 3801, the key is coming with the id 0100, making it impossible to proceed in the following missions.

In the second photo, it would be the door that you could open with the supposed key.

### How to Reproduce?

Start the quest, in this quest a series of keys will be found and doors will need to be opened.
However, during the process, when obtaining the second key, which should come with the ID 3801, you will notice that your ID is wrong (0100). However, the door that this key should open is with the correct ID, so it is not possible to open it with the wrong key and proceed with the quest.

### Attach any relevant file

![image](https://user-images.githubusercontent.com/11935651/161267382-5d6d7fcf-91a4-46a9-880c-c4a13b48e14a.png)
![image](https://user-images.githubusercontent.com/11935651/161267397-3a4fd052-4eef-4dc6-b5b2-8afe9b81adf4.png)

### Version

12.x (Default)

### What OS are you seeing the problem on?

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucascebertin** [comment]
@victorperin found what happens to this one.

Please look into the file `startup/others/tables/chest.lua` and you going to find some ChestUnique items that will have properties like `storage` and `keyAction`.
To workaround the problem, try to add this line:
```lua
keyAction = Storage.Quest.Key.ID3801
``` 
And you will have something like this:
```lua
	[5004] = {
		isKey = true,
		itemId = 2472,
		itemPos = {x = 32648, y = 31905, z = 3},
		container = 2853,
		reward = {{2970, 1}},
		weight = 44,
		storage = Storage.Quest.Key.ID3801,
		keyAction = Storage.Quest.Key.ID3801
	},
```

The same workaround applies to `ID4502`.

Looks like there is a path in the code (I mean, a `if` condition) that will try to use `keyAction` instead of `storage` property.
You can check for youself in the file `scripts/actions/system/quest_reward_common.lua` at the line 158:
```lua
		if setting.container then
			local addContainerItemParams = {
				player = player,
				itemid = itemid,
				count = count,
				weight = setting.weight,
				storage = setting.storage,
				action = setting.keyAction, -- in particular, this line... see, it's trying to use that keyAction
				itemBagName = itemBagName,
				containerReward = itemBag
			}

			if not playerAddContainerItem(addContainerItemParams, item) then
				return true
			end
		end
```

Hope that helps to solve your problem.

**Comment by andersonfaaria** [comment]
@lucascebertin can you open a PR?

**Comment by lucascebertin** [comment]
Sure thing @andersonfaaria, I'll do that as soon as I can.

**Comment by lucascebertin** [comment]
@andersonfaaria, done, feel free to comment or point out something missing on that pull request.
Thanks.
