### ISSUE TITLE
chemar travel not working

### ISSUE THREAD

**Issue by rigis1** [opentibiabr/otservbr-global#666]
### Priority

Low

### Area

- [X] Datapack
- [ ] Source
- [ ] Map
- [ ] Other

### What happened?

Travel not working, could be #594
![2022-06-28 (1)](https://user-images.githubusercontent.com/22598283/176283152-b58f7eb2-967e-4d9a-96cd-abb248e9ddd8.png)

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sircurse** [comment]
Hi @rigis1, I highly recommend you to review your datapack, the quest was reviewed to fix wrong things that was wrote and make it even more real to the global, due to it some of the storages have been changed and it will be updated automatically on startup, but also there are new storages created and thus this new storages cannot be updated of course, so to fix it you can add the missing storages to players manually or create a script/talkaction to do so, you can even use as example the freequests.lua as example to create that script.
Btw.. I have just tested Chemar and it is working as expected, so it might be the storage (72724, 2) that is missing in your player.

**Comment by rigis1** [comment]
Hi, @sircurse, setting up storage (72724, 2) not helping at all, i made two new servers and on both same results.
Settings:
1. Release canary and new datapack from main
2. Newest nightly builds for Windows and new datapack from main
