### ISSUE TITLE
Crash Server with Farmiliar at Thais Temple

### ISSUE THREAD

**Issue by tutbarao** [opentibiabr/otservbr-global#702]
### Priority

Critical

### Area

- [ ] Datapack
- [X] Source
- [ ] Map
- [ ] Other

### What happened?

Crasha server when doing reload scripts or /save with GOD having some Farmiliar in Thais Temple.

try reloading scripts or /save a few times with the familiar summoned to the temple.

### What OS are you seeing the problem on?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dudantas** [comment]
> ### Priority
> Critical
> 
> ### Area
> * [ ]  Datapack
> * [x]  Source
> * [ ]  Map
> * [ ]  Other
> 
> ### What happened?
> Crasha server when doing reload scripts or /save with GOD having some Farmiliar in Thais Temple.
> 
> try reloading scripts or /save a few times with the familiar summoned to the temple.
> 
> ### What OS are you seeing the problem on?
> Windows 10
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

![image](https://user-images.githubusercontent.com/8551443/180805972-78bc1982-ba5d-4530-a63d-0b4282071a48.png)

You need to be more specific
Try to get the crash log and send it, I couldn't reproduce this possible crash
Make sure it wasn't some change you made that caused this, as it's a very difficult behavior to reproduce, there is no code that could cause an unhandled exception between familiar and protection zone (or thais temple)

Try to reproduce the problem with the clean base (download from git, without any changes from you), if you can, get the crash log and send it here
Also try to find a pattern, because the way you reported it is impossible to reach a definitive conclusion.

**Comment by dudantas** [comment]
> > ### Priority
> > Critical
> > ### Area
> > 
> > * [ ]   Datapack
> > * [x]   Source
> > * [ ]   Map
> > * [ ]   Other
> > 
> > ### What happened?
> > Crasha server when doing reload scripts or /save with GOD having some Farmiliar in Thais Temple.
> > try reloading scripts or /save a few times with the familiar summoned to the temple.
> > ### What OS are you seeing the problem on?
> > Windows 10
> > ### Code of Conduct
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> 
> ![image](https://user-images.githubusercontent.com/8551443/180805972-78bc1982-ba5d-4530-a63d-0b4282071a48.png)
> 
> You need to be more specific Try to get the crash log and send it, I couldn't reproduce this possible crash Make sure it wasn't some change you made that caused this, as it's a very difficult behavior to reproduce, there is no code that could cause an unhandled exception between familiar and protection zone (or thais temple)

Try to reproduce the problem with the clean base (download from git, without any changes from you), if you can, get the crash log and send it here
Also try to find a pattern, because the way you reported it is impossible to reach a definitive conclusion.
