### ISSUE TITLE
Bug related to house. Game crash!

### ISSUE THREAD

**Issue by cristianso** [opentibiabr/otservbr-global#724]
Since I was trying to find out new things, I will edit here everything that I found out.
There is literally every step I did.

**Reproductions step:**
**1-** Download the "branch: develop" of this base;
**2-** Compile on Ubuntu 14.04;
**3-** Download myaac latest version;
**4-** Use schema.sql that is inside this base;
**5-** Set config.lua "houseRentPeriod="weekly" or "monthly" (did not test "daily" or "annual");
**6-** Use the talkaction !buyhouse to buy the house (I've tested tons of talkactions that buy houses, all of them I have the same result);
**7-** Use global map that is inside of this base;
**8-** Start your server;
**9-** Get enough money in your balance and buy a house;
**10-** After you buy the house, restart your server;
**11-** Next time you try to login, your client is going to debug and you have to delete your char from the game. (Sometimes you can login to the game, but you must try tons of times);

**Considerations:** Doesn't matter where your char is or what house you bought, the result is the same. You can buy the house and teleport to anywhere in the map, your game is going to bug when you restart the game.

**Client**: 12
**OS**: Ubuntu 14.04

**Comment by cristianso** [comment]
Seems like a random thing. I tried to redo these steps and this time did not work. There is something more that is triggleling this bug, but I don't know yet.

**Comment by dudantas** [comment]
You may have made a change to your base that is causing this ...
Try to follow the issue recommendations (when you will open it)
Download the latest CLEAN base without any changes. Compile it, use the CLEAN database and see if the debug will occur. Most of these random debugs are not due to any base issues, but to some script you add.

**Comment by christiangamaesilva** [comment]
Bro..... Did you even TRY?! I just compiled for the third time a full clean base, didn't edit anything at all.
IT WILL CRASH! 
Please, before saying that, try before, okay?

**Comment by christiangamaesilva** [comment]
Just change houseRentPeriod from  = "never" to "weekly", or "monthly" and then buy a house ingame, restart the server and try to login again. Your game is going to CRASH! You added the label unconfirmed and didn't even try doing the steps I said....

**Comment by dudantas** [comment]
> Just change houseRentPeriod from = "never" to "weekly", or "monthly" and then buy a house ingame, restart the server and try to login again. Your game is going to CRASH! You added the label unconfirmed and didn't even try doing the steps I said....

You who have to give information. I don't read minds.
When creating the issue has a lot of information, you should tell how you reproduced the bug and not just say you found it.

And you said yourself that the problem is not that, that stopped giving. How do you think I will handle this information? Without diagnosis there is no way to test.

Besides, as I mentioned, your issue does not follow the parameter you request at the time of creation.

It has been tested twice and the problem has not occurred here, which leads us to believe that you are doing something wrong, or if you have a concrete diagnosis, it may make it easier for us to analyze and later resolve.

**Comment by dudantas** [comment]
> Just change houseRentPeriod from = "never" to "weekly", or "monthly" and then buy a house ingame, restart the server and try to login again. Your game is going to CRASH! You added the label unconfirmed and didn't even try doing the steps I said....

Ok, I will test!

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/68148822-7abe4300-ff1b-11e9-90dc-0273928fea72.png)

Another thing, you edited the steps, which I followed before and didn't debug. You should report the issue and not wait for me to guess.
That's why I marked it as unconfirmed

**Comment by christiangamaesilva** [comment]
I edited it just after I posted here, didn't take long. The reproductions steps wasn't really accurate, but now it is. I am sure if you do these steps you are going to have the same bug as me.
Also, there is no need to make a house in RME, you can buy a house from global server too. I just tested it right now.

**Comment by dudantas** [comment]
You edited 7 hours later, I tested right after you published. Anyway, I'm already doing the tests again, in a moment give a positioning.

**Comment by christiangamaesilva** [comment]
Yea, you are right. I thought I edited just after I posted it here. I am sorry. Anyway, you can test now and you will have the same issue as me, im sure, since I am using 100% default base, database and data.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/68154517-6fbce000-ff26-11e9-920d-e792ead81c3e.png)

I did exactly what you said!
With ADM, I am creating a char to test.
I used the most current clean base, and followed the Majesty tutorial. I installed everything from 0, from repository, to website, database ... Etc. No debug.

https://forums.otserv.com.br/index.php?/forums/topic/167722-windowsmysqlotservbr-global-uniform-server-gesioraac2012/

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/68155925-7bf66c80-ff29-11e9-8b22-d2cef7d0fa65.png)
![image](https://user-images.githubusercontent.com/8551443/68155935-80bb2080-ff29-11e9-9fb2-ab20c22eedb5.png)
It's ok!

**Comment by dudantas** [comment]
As I said, it is not a base bug.
There is no sense in this bug.

**Comment by christiangamaesilva** [comment]
Did you set it to weekly and restart the server just after you buy the house?
Because another friend of mine, from another location just tried now and is having the same issue as me. And he think he knows what is causing it, so... I think you skipped a step.

**Comment by dudantas** [comment]
![image](https://user-images.githubusercontent.com/8551443/68156902-684c0580-ff2b-11e9-85df-dbda7e46227c.png)

Yes. I did exactly as you said.
I didn't skip anything.
I changed the config.lua
I made a new house, as you can see in the look.

I bought and restarted the server. I logged in normally.

**Comment by christiangamaesilva** [comment]
Well... Something is happening, I am sure it is nothing wrong with my bases, I just downloaded it from here and my friend too. What OS are you using? Aren't you interesting about what is causing it? I wouldn't ignore it, since it happened with me and another person already.

**Comment by christiangamaesilva** [comment]
And are you really using the same base as me, the original one without any changes? Because as I can see from this screenshot, you have different values for "timebetweenactions", so I imagine you aren't using the default base, you've already changed something.

**Comment by dudantas** [comment]
The config.lua is ignored by github desktop, so it has different values. But that has nothing to do with the rest of the base. I did git pull just before testing and I'm using the github cloned repository, I'm absolutely sure it's up to date. The config is not a parameter.

**Comment by lBaah** [comment]
- Post all your config.lua related to house.
- Look at the door house and paste it here.
- Post your RME version, also the proprieties of the house.
- Post here a screenshot of the house you made in RME
- Where are your character when you login again? In the house, in the bed or outside the house?
- What happens with character bank balance when that occurs?
- There was any item inside the house?

**Comment by dudantas** [comment]
And price per sqm

**Comment by christiangamaesilva** [comment]
1 - Config.lua;
`-- Combat settings
-- NOTE: valid values for worldType are: "pvp", "no-pvp" and "pvp-enforced"
worldType = "pvp"
hotkeyAimbotEnabled = true
protectionLevel = 7
pzLocked = 60 * 1000
removeChargesFromRunes = true
removeChargesFromPotions = true
removeWeaponAmmunition = true
removeWeaponCharges = true
timeToDecreaseFrags = 45 * 24 * 60 * 60
whiteSkullTime = 15 * 60 * 1000
stairJumpExhaustion = 2 * 1000
experienceByKillingPlayers = false
expFromPlayersLevelRange = 75
dayKillsToRedSkull = 3
weekKillsToRedSkull = 5
monthKillsToRedSkull = 10
redSkullDuration = 30
blackSkullDuration = 45
orangeSkullDuration = 7

-- Connection Config
-- NOTE: maxPlayers set to 0 means no limit
-- NOTE: MaxPacketsPerSeconds if you change you will be subject to bugs by WPE, keep the default value of 25
ip = "127.0.0.1"
bindOnlyGlobalAddress = false
loginProtocolPort = 7171
gameProtocolPort = 7172
statusProtocolPort = 7171
maxPlayers = 0
motd = "Bem vindo ao Open-TibiaBR!"
onePlayerOnlinePerAccount = true
allowClones = false
serverName = "Open-TibiaBR"
statusTimeout = 5 * 1000
replaceKickOnLogin = true
maxPacketsPerSecond = 25
maxItem = 2000
maxContainer = 100

-- Version Manual
clientVersionMin = 1100
clientVersionMax = 1200
clientVersionStr = "Only support outdated 10.00 and version 12.00"

-- Depot Limit
freeDepotLimit = 2000
premiumDepotLimit = 10000
depotBoxes = 17

-- GameStore
gamestoreByModules = true

-- Quest Sytem
loadQuestLua = true

-- Expert Pvp Config
expertPvp = false

-- Deaths
-- NOTE: Leave deathLosePercent as -1 if you want to use the default
-- death penalty formula. For the old formula, set it to 10. For
-- no skill/experience loss, set it to 0.
deathLosePercent = -1

-- Houses
-- NOTE: set housePriceEachSQM to -1 to disable the ingame buy house functionality
housePriceEachSQM = 1000
houseRentPeriod = "weekly"

-- Item Usage
-- Do not touch here
-- Avoid use of WIPE program to crash the distro
timeBetweenActions = 500
timeBetweenExActions = 700

-- Map
-- NOTE: set mapName WITHOUT .otbm at the end
-- NOTE: unzip the map world.rar
mapName = "otservbr"
mapAuthor = "Open-TibiaBR"

-- Market
marketOfferDuration = 30 * 24 * 60 * 60
premiumToCreateMarketOffer = true
checkExpiredMarketOffersEachMinutes = 60
maxMarketOffersAtATimePerPlayer = 100

-- MySQL
mysqlHost = "127.0.0.1"
mysqlUser = "root"
mysqlPass = ""
mysqlDatabase = "otservbr"
mysqlPort = 3306
mysqlSock = ""

-- Misc.
allowChangeOutfit = true
freePremium = true
kickIdlePlayerAfterMinutes = 15
idleWarningTime = 10 * 60 * 1000
idleKickTime = 15 * 60 * 1000
maxMessageBuffer = 4
emoteSpells = false
classicEquipmentSlots = false
allowWalkthrough = true
coinPacketSize = 25
coinImagesURL = "http://localhost/images/store/"
classicAttackSpeed = false
showScriptsLogInConsole = false

-- Server Save
notifyServerSave = true
cleanMapAtServerSave = false
closeAtServerSave = false
shutdownAtServerSave = true     -- If you set close and shutdown to 'true' it will close and then shutdown the server.

-- Rates
-- NOTE: rateExp is not used if you have enabled stages in data/XML/stages.xml
rateExp = 1
rateSkill = 50
rateLoot = 3
rateMagic = 25
rateSpawn = 1

-- Monster rates
rateMonsterHealth = 1.0
rateMonsterAttack = 1.0
rateMonsterDefense = 1.0

-- Monsters
deSpawnRange = 2
deSpawnRadius = 50

-- Stamina
staminaSystem = true

-- Scripts
warnUnsafeScripts = true
convertUnsafeScripts = true

-- Startup
-- NOTE: defaultPriority only works on Windows and sets process
-- priority, valid values are: "normal", "above-normal", "high"
defaultPriority = "high"
startupDatabaseOptimization = true

-- Status server information
ownerName = "OTServBR-Global"
ownerEmail = ""
url = "https://github.com/opentibiabr/OTServBR-Global"
location = "South America"
`
**2-** This is irrelevant, since it happens with ANY house of the game (global map);
**3-** Rme is also irrelevant because it happens to the official global map, the one that I get when I download this base;
**4-** Same as 3-;
**5-** Anywhere. Doesn't matter where I am, it will crash anywhere of the map;
**6-** My bank account reduces the exact amount that I need to pay for the rent;
**7-** It happens with any kind of house in any town or map;

**Comment by christiangamaesilva** [comment]
Pelo o que vi, você é br. Vou continuar falando em inglês pois pode ajudar outros. Porém, cara, eu sei do que estou falando. Eu tenho certeza absoluta que compilei do jeito que vocês mandam e só fiz startar o tfs, não tem como eu ter feito algo de errado. Enfim, vou falar em inglês apenas aqui.

**Comment by christiangamaesilva** [comment]
I edited once again with new informations that may be useful, please check it again. Also, see what OS I am using and what client I am using.

**Comment by dudantas** [comment]
Tente seguir este tutorial do Majesty: https://forums.otserv.com.br/index.php?/forums/topic/167722-windowsmysqlotservbr-global-uniform-server-gesioraac2012/

Use o gesior e veja se dá a mesma coisa. Eu segui o tutorial a risca e deu tudo certo. Imaginei que poderia ser por eu não ter feito dentro da house, mas você disse que não tem necessidade de estar na house. Porém, testei em Windows. 
A interface do Issue pede que você diga seu S.O e várias outras informações, teria facilitado muito se você tivesse colocado essas informações antes. O @lBaah deve testar no Linux e dizer se vai dar a mesma coisa. Até lá, vamos aguardar. 
Majesty também testou (em Windows) e não deu isso.

**Comment by dudantas** [comment]
Você tem que considederar que pode não ser um problema na base. Tente usar o tutorial que falei com Gesior, se não der, tente com Xampp ou outro programa, não acho que o problema seja na base, pois sendo assim não deveria ocorrer apenas com você, já que está diretamente relacionado a houses, pelo que você disse. Tente também utilizar o cliente 10 e ver se dá o debug...

**Comment by christiangamaesilva** [comment]
Eu estou levando realmente a sério pois um amigo meu que é inclusive contribuidor aqui, testou com ele e a equipe dele e conseguiram obter o mesmo bug. Eles estão trabalhando pra verificar o que pode ser. Eu, nesse exato momento, estou reinstalando tudo mais uma vez, porém agora no ubuntu 18.04 que é mais atualizado e vou ver se acontece o mesmo. Eu usei o myaac pois no forum do Majesty ele orientou o uso do myaac, porém tentarei com gesior também.

**Comment by dudantas** [comment]
Tenta usar o cliente 10. Tem que ir descartando as possibilidades...

**Comment by lBaah** [comment]
Aparentemente não é um erro relacionado à houses.
Não sei porque esse erro acontece ao mudar o período de pagamentos. Veja a função payHouses em house.cpp
Fato: mesmo removendo a house o cliente ainda toma crash, o que me leva a crer que existe informações que não estão sendo passadas ao cliente de forma completa.

Ainda estou investigando.

**Comment by lBaah** [comment]
Preciso de mais informações relacionadas ao balance do personagem.
Por gentileza, replique o problema em mais de um personagem e poste os dados das houses e desses players. (os respectivos registros no banco de dados)

**Comment by christiangamaesilva** [comment]
Como faço pra enviar o registro do banco de dados aqui? Eu sabendo como faz, eu mando tudo aqui pra você.

**Comment by lBaah** [comment]
Pode ser por print mesmo.

**Comment by dudantas2** [comment]
@cristianso está por aí? acho que resolvi o bug e gostaria que você testasse comigo.

**Comment by dudantas** [comment]
@cristianso  está por aí? acho que resolvi o bug e gostaria que você testasse comigo.

**Comment by dudantas** [comment]
Fixed in the https://github.com/opentibiabr/otservbr-global/commit/ad3fe2ed0d771ff66030650650ff8f561d359e26
