### ISSUE TITLE
Elemental damage bug with the critical, without critical, with magics (exori, exori gran and more)

### ISSUE THREAD

**Issue by luisbill1** [opentibiabr/otservbr-global#789]
The elemental damage of all weapons don't do the same damage as others weapons that have normal physical damage.
The damage of a normal weapon is SO MUCH BIGGER than a elemental weapon, all those hits are bugged
OBS: I'm talking about all weapons that have the elemental damage without imbuiment elemental, exemple: Cobra axe, Falcon Battleaxe and more..

**Comment by Lycanzito** [comment]
teste 1
15:19 A leaf loses 729 hitpoints due to your attack.
15:19 A leaf loses 686 hitpoints due to your attack.
15:19 A leaf loses 669 hitpoints due to your attack.
15:19 A leaf loses 718 hitpoints due to your attack.
15:19 A leaf loses 672 hitpoints due to your attack.
15:19 A leaf loses 690 hitpoints due to your attack.
15:19 A leaf loses 656 hitpoints due to your attack.
15:19 A leaf loses 666 hitpoints due to your attack.
15:19 A leaf loses 678 hitpoints due to your attack.
15:19 A leaf loses 700 hitpoints due to your attack.
15:19 A leaf loses 665 hitpoints due to your attack.
15:19 A leaf loses 695 hitpoints due to your attack.
15:19 A leaf loses 698 hitpoints due to your attack.
15:19 A leaf loses 730 hitpoints due to your attack.
15:19 A leaf loses 740 hitpoints due to your attack.
15:19 A leaf loses 710 hitpoints due to your attack.
15:19 A leaf loses 658 hitpoints due to your attack.
15:19 A leaf loses 697 hitpoints due to your attack.
15:19 A leaf loses 690 hitpoints due to your attack.
15:19 A leaf loses 725 hitpoints due to your attack.
15:19 A leaf loses 666 hitpoints due to your attack.
15:19 A leaf loses 715 hitpoints due to your attack.
15:19 A leaf loses 700 hitpoints due to your attack.
15:19 A leaf loses 643 hitpoints due to your attack.
15:19 A leaf loses 675 hitpoints due to your attack.
15:19 A leaf loses 733 hitpoints due to your attack.
15:19 A leaf loses 711 hitpoints due to your attack.
15:19 A leaf loses 701 hitpoints due to your attack.
15:19 A leaf loses 712 hitpoints due to your attack.
15:19 A leaf loses 709 hitpoints due to your attack.
15:19 A leaf loses 675 hitpoints due to your attack.
15:19 A leaf loses 685 hitpoints due to your attack.
15:19 You see an umbral master axe (Atk:53, Def:30 +3, axe fighting +1).
Imbuements: (Empty Slot, Empty Slot).
It weighs 80.00 oz.



teste 2
15:19 A leaf loses 484 hitpoints due to your attack.
15:19 A leaf loses 317 hitpoints due to your attack.
15:19 A leaf loses 487 hitpoints due to your attack.
15:19 A leaf loses 531 hitpoints due to your attack.
15:19 A leaf loses 408 hitpoints due to your attack.
15:19 A leaf loses 622 hitpoints due to your attack.
15:19 A leaf loses 314 hitpoints due to your attack.
15:19 A leaf loses 549 hitpoints due to your attack.
15:19 A leaf loses 665 hitpoints due to your attack.
15:19 A leaf loses 561 hitpoints due to your attack.
15:19 A leaf loses 324 hitpoints due to your attack.
15:19 A leaf loses 413 hitpoints due to your attack.
15:20 A leaf loses 469 hitpoints due to your attack.
15:20 A leaf loses 316 hitpoints due to your attack.
15:20 A leaf loses 548 hitpoints due to your attack.
15:20 A leaf loses 506 hitpoints due to your attack.
15:20 A leaf loses 562 hitpoints due to your attack.
15:20 A leaf loses 598 hitpoints due to your attack.
15:20 A leaf loses 554 hitpoints due to your attack.
15:20 A leaf loses 518 hitpoints due to your attack.
15:20 A leaf loses 622 hitpoints due to your attack.
15:20 A leaf loses 475 hitpoints due to your attack.
15:20 A leaf loses 506 hitpoints due to your attack.
15:20 A leaf loses 568 hitpoints due to your attack.
15:20 A leaf loses 552 hitpoints due to your attack.
15:20 A leaf loses 769 hitpoints due to your attack.
15:20 A leaf loses 392 hitpoints due to your attack.
15:20 A leaf loses 395 hitpoints due to your attack.
15:20 A leaf loses 352 hitpoints due to your attack.
15:20 A leaf loses 684 hitpoints due to your attack.
15:20 You see a Cobra Axe (Atk:8 physical + 44 ice, Def:29 +2, axe fighting +2).
It can only be wielded properly by knights.
Imbuements: (Empty Slot, Empty Slot).
It weighs 40.00 oz.
15:21 A leaf loses 559 hitpoints due to your attack.
15:21 A leaf loses 559 hitpoints due to your attack.
15:21 A leaf loses 453 hitpoints due to your attack.
15:21 A leaf loses 501 hitpoints due to your attack.
15:21 A leaf loses 458 hitpoints due to your attack.
15:21 A leaf loses 512 hitpoints due to your attack.
15:21 A leaf loses 678 hitpoints due to your attack.
15:21 A leaf loses 490 hitpoints due to your attack.
15:21 A leaf loses 343 hitpoints due to your attack.
15:21 A leaf loses 755 hitpoints due to your attack.
15:21 A leaf loses 610 hitpoints due to your attack.
15:21 A leaf loses 646 hitpoints due to your attack.
15:21 A leaf loses 708 hitpoints due to your attack.
15:21 A leaf loses 486 hitpoints due to your attack.
15:21 A leaf loses 600 hitpoints due to your attack.
15:21 A leaf loses 471 hitpoints due to your attack.
15:21 A leaf loses 562 hitpoints due to your attack.
15:21 A leaf loses 538 hitpoints due to your attack.
15:21 A leaf loses 491 hitpoints due to your attack.
15:21 A leaf loses 474 hitpoints due to your attack.
15:21 A leaf loses 479 hitpoints due to your attack.
15:21 A leaf loses 448 hitpoints due to your attack.
15:21 A leaf loses 591 hitpoints due to your attack.
15:21 A leaf loses 659 hitpoints due to your attack.
15:21 A leaf loses 320 hitpoints due to your attack.
15:21 A leaf loses 550 hitpoints due to your attack.
15:21 A leaf loses 647 hitpoints due to your attack.
15:21 A leaf loses 468 hitpoints due to your attack.
15:21 A leaf loses 697 hitpoints due to your attack.
15:21 A leaf loses 567 hitpoints due to your attack.
15:21 A leaf loses 754 hitpoints due to your attack.
15:21 A leaf loses 542 hitpoints due to your attack.
15:21 A leaf loses 670 hitpoints due to your attack.


Usando Exori gran ~
De fato tem um pouco de maior variação com armas elementais.
Chegando a ser o dobro de diferença, hits com armas elementais 15:19 A leaf loses 317 hitpoints due to your attack.
e hits com 15:19 A leaf loses 730 hitpoints due to your attack. com outra arma.

**Comment by luisbill1** [comment]
> teste 1
> 15:19 A leaf loses 729 hitpoints due to your attack.
> 15:19 A leaf loses 686 hitpoints due to your attack.
> 15:19 A leaf loses 669 hitpoints due to your attack.
> 15:19 A leaf loses 718 hitpoints due to your attack.
> 15:19 A leaf loses 672 hitpoints due to your attack.
> 15:19 A leaf loses 690 hitpoints due to your attack.
> 15:19 A leaf loses 656 hitpoints due to your attack.
> 15:19 A leaf loses 666 hitpoints due to your attack.
> 15:19 A leaf loses 678 hitpoints due to your attack.
> 15:19 A leaf loses 700 hitpoints due to your attack.
> 15:19 A leaf loses 665 hitpoints due to your attack.
> 15:19 A leaf loses 695 hitpoints due to your attack.
> 15:19 A leaf loses 698 hitpoints due to your attack.
> 15:19 A leaf loses 730 hitpoints due to your attack.
> 15:19 A leaf loses 740 hitpoints due to your attack.
> 15:19 A leaf loses 710 hitpoints due to your attack.
> 15:19 A leaf loses 658 hitpoints due to your attack.
> 15:19 A leaf loses 697 hitpoints due to your attack.
> 15:19 A leaf loses 690 hitpoints due to your attack.
> 15:19 A leaf loses 725 hitpoints due to your attack.
> 15:19 A leaf loses 666 hitpoints due to your attack.
> 15:19 A leaf loses 715 hitpoints due to your attack.
> 15:19 A leaf loses 700 hitpoints due to your attack.
> 15:19 A leaf loses 643 hitpoints due to your attack.
> 15:19 A leaf loses 675 hitpoints due to your attack.
> 15:19 A leaf loses 733 hitpoints due to your attack.
> 15:19 A leaf loses 711 hitpoints due to your attack.
> 15:19 A leaf loses 701 hitpoints due to your attack.
> 15:19 A leaf loses 712 hitpoints due to your attack.
> 15:19 A leaf loses 709 hitpoints due to your attack.
> 15:19 A leaf loses 675 hitpoints due to your attack.
> 15:19 A leaf loses 685 hitpoints due to your attack.
> 15:19 You see an umbral master axe (Atk:53, Def:30 +3, axe fighting +1).
> Imbuements: (Empty Slot, Empty Slot).
> It weighs 80.00 oz.
> 
> teste 2
> 15:19 A leaf loses 484 hitpoints due to your attack.
> 15:19 A leaf loses 317 hitpoints due to your attack.
> 15:19 A leaf loses 487 hitpoints due to your attack.
> 15:19 A leaf loses 531 hitpoints due to your attack.
> 15:19 A leaf loses 408 hitpoints due to your attack.
> 15:19 A leaf loses 622 hitpoints due to your attack.
> 15:19 A leaf loses 314 hitpoints due to your attack.
> 15:19 A leaf loses 549 hitpoints due to your attack.
> 15:19 A leaf loses 665 hitpoints due to your attack.
> 15:19 A leaf loses 561 hitpoints due to your attack.
> 15:19 A leaf loses 324 hitpoints due to your attack.
> 15:19 A leaf loses 413 hitpoints due to your attack.
> 15:20 A leaf loses 469 hitpoints due to your attack.
> 15:20 A leaf loses 316 hitpoints due to your attack.
> 15:20 A leaf loses 548 hitpoints due to your attack.
> 15:20 A leaf loses 506 hitpoints due to your attack.
> 15:20 A leaf loses 562 hitpoints due to your attack.
> 15:20 A leaf loses 598 hitpoints due to your attack.
> 15:20 A leaf loses 554 hitpoints due to your attack.
> 15:20 A leaf loses 518 hitpoints due to your attack.
> 15:20 A leaf loses 622 hitpoints due to your attack.
> 15:20 A leaf loses 475 hitpoints due to your attack.
> 15:20 A leaf loses 506 hitpoints due to your attack.
> 15:20 A leaf loses 568 hitpoints due to your attack.
> 15:20 A leaf loses 552 hitpoints due to your attack.
> 15:20 A leaf loses 769 hitpoints due to your attack.
> 15:20 A leaf loses 392 hitpoints due to your attack.
> 15:20 A leaf loses 395 hitpoints due to your attack.
> 15:20 A leaf loses 352 hitpoints due to your attack.
> 15:20 A leaf loses 684 hitpoints due to your attack.
> 15:20 You see a Cobra Axe (Atk:8 physical + 44 ice, Def:29 +2, axe fighting +2).
> It can only be wielded properly by knights.
> Imbuements: (Empty Slot, Empty Slot).
> It weighs 40.00 oz.
> 15:21 A leaf loses 559 hitpoints due to your attack.
> 15:21 A leaf loses 559 hitpoints due to your attack.
> 15:21 A leaf loses 453 hitpoints due to your attack.
> 15:21 A leaf loses 501 hitpoints due to your attack.
> 15:21 A leaf loses 458 hitpoints due to your attack.
> 15:21 A leaf loses 512 hitpoints due to your attack.
> 15:21 A leaf loses 678 hitpoints due to your attack.
> 15:21 A leaf loses 490 hitpoints due to your attack.
> 15:21 A leaf loses 343 hitpoints due to your attack.
> 15:21 A leaf loses 755 hitpoints due to your attack.
> 15:21 A leaf loses 610 hitpoints due to your attack.
> 15:21 A leaf loses 646 hitpoints due to your attack.
> 15:21 A leaf loses 708 hitpoints due to your attack.
> 15:21 A leaf loses 486 hitpoints due to your attack.
> 15:21 A leaf loses 600 hitpoints due to your attack.
> 15:21 A leaf loses 471 hitpoints due to your attack.
> 15:21 A leaf loses 562 hitpoints due to your attack.
> 15:21 A leaf loses 538 hitpoints due to your attack.
> 15:21 A leaf loses 491 hitpoints due to your attack.
> 15:21 A leaf loses 474 hitpoints due to your attack.
> 15:21 A leaf loses 479 hitpoints due to your attack.
> 15:21 A leaf loses 448 hitpoints due to your attack.
> 15:21 A leaf loses 591 hitpoints due to your attack.
> 15:21 A leaf loses 659 hitpoints due to your attack.
> 15:21 A leaf loses 320 hitpoints due to your attack.
> 15:21 A leaf loses 550 hitpoints due to your attack.
> 15:21 A leaf loses 647 hitpoints due to your attack.
> 15:21 A leaf loses 468 hitpoints due to your attack.
> 15:21 A leaf loses 697 hitpoints due to your attack.
> 15:21 A leaf loses 567 hitpoints due to your attack.
> 15:21 A leaf loses 754 hitpoints due to your attack.
> 15:21 A leaf loses 542 hitpoints due to your attack.
> 15:21 A leaf loses 670 hitpoints due to your attack.
> 
> Usando Exori gran ~
> De fato tem um pouco de maior variação com armas elementais.
> Chegando a ser o dobro de diferença, hits com armas elementais 15:19 A leaf loses 317 hitpoints due to your attack.
> e hits com 15:19 A leaf loses 730 hitpoints due to your attack. com outra arma.

Sim, a variação é muito grande...
Não sei onde bem mexer para ajeitar isso, creio que seja na source o problema

**Comment by Lycanzito** [comment]
> > teste 1
> > 15:19 A leaf loses 729 hitpoints due to your attack.
> > 15:19 A leaf loses 686 hitpoints due to your attack.
> > 15:19 A leaf loses 669 hitpoints due to your attack.
> > 15:19 A leaf loses 718 hitpoints due to your attack.
> > 15:19 A leaf loses 672 hitpoints due to your attack.
> > 15:19 A leaf loses 690 hitpoints due to your attack.
> > 15:19 A leaf loses 656 hitpoints due to your attack.
> > 15:19 A leaf loses 666 hitpoints due to your attack.
> > 15:19 A leaf loses 678 hitpoints due to your attack.
> > 15:19 A leaf loses 700 hitpoints due to your attack.
> > 15:19 A leaf loses 665 hitpoints due to your attack.
> > 15:19 A leaf loses 695 hitpoints due to your attack.
> > 15:19 A leaf loses 698 hitpoints due to your attack.
> > 15:19 A leaf loses 730 hitpoints due to your attack.
> > 15:19 A leaf loses 740 hitpoints due to your attack.
> > 15:19 A leaf loses 710 hitpoints due to your attack.
> > 15:19 A leaf loses 658 hitpoints due to your attack.
> > 15:19 A leaf loses 697 hitpoints due to your attack.
> > 15:19 A leaf loses 690 hitpoints due to your attack.
> > 15:19 A leaf loses 725 hitpoints due to your attack.
> > 15:19 A leaf loses 666 hitpoints due to your attack.
> > 15:19 A leaf loses 715 hitpoints due to your attack.
> > 15:19 A leaf loses 700 hitpoints due to your attack.
> > 15:19 A leaf loses 643 hitpoints due to your attack.
> > 15:19 A leaf loses 675 hitpoints due to your attack.
> > 15:19 A leaf loses 733 hitpoints due to your attack.
> > 15:19 A leaf loses 711 hitpoints due to your attack.
> > 15:19 A leaf loses 701 hitpoints due to your attack.
> > 15:19 A leaf loses 712 hitpoints due to your attack.
> > 15:19 A leaf loses 709 hitpoints due to your attack.
> > 15:19 A leaf loses 675 hitpoints due to your attack.
> > 15:19 A leaf loses 685 hitpoints due to your attack.
> > 15:19 You see an umbral master axe (Atk:53, Def:30 +3, axe fighting +1).
> > Imbuements: (Empty Slot, Empty Slot).
> > It weighs 80.00 oz.
> > teste 2
> > 15:19 A leaf loses 484 hitpoints due to your attack.
> > 15:19 A leaf loses 317 hitpoints due to your attack.
> > 15:19 A leaf loses 487 hitpoints due to your attack.
> > 15:19 A leaf loses 531 hitpoints due to your attack.
> > 15:19 A leaf loses 408 hitpoints due to your attack.
> > 15:19 A leaf loses 622 hitpoints due to your attack.
> > 15:19 A leaf loses 314 hitpoints due to your attack.
> > 15:19 A leaf loses 549 hitpoints due to your attack.
> > 15:19 A leaf loses 665 hitpoints due to your attack.
> > 15:19 A leaf loses 561 hitpoints due to your attack.
> > 15:19 A leaf loses 324 hitpoints due to your attack.
> > 15:19 A leaf loses 413 hitpoints due to your attack.
> > 15:20 A leaf loses 469 hitpoints due to your attack.
> > 15:20 A leaf loses 316 hitpoints due to your attack.
> > 15:20 A leaf loses 548 hitpoints due to your attack.
> > 15:20 A leaf loses 506 hitpoints due to your attack.
> > 15:20 A leaf loses 562 hitpoints due to your attack.
> > 15:20 A leaf loses 598 hitpoints due to your attack.
> > 15:20 A leaf loses 554 hitpoints due to your attack.
> > 15:20 A leaf loses 518 hitpoints due to your attack.
> > 15:20 A leaf loses 622 hitpoints due to your attack.
> > 15:20 A leaf loses 475 hitpoints due to your attack.
> > 15:20 A leaf loses 506 hitpoints due to your attack.
> > 15:20 A leaf loses 568 hitpoints due to your attack.
> > 15:20 A leaf loses 552 hitpoints due to your attack.
> > 15:20 A leaf loses 769 hitpoints due to your attack.
> > 15:20 A leaf loses 392 hitpoints due to your attack.
> > 15:20 A leaf loses 395 hitpoints due to your attack.
> > 15:20 A leaf loses 352 hitpoints due to your attack.
> > 15:20 A leaf loses 684 hitpoints due to your attack.
> > 15:20 You see a Cobra Axe (Atk:8 physical + 44 ice, Def:29 +2, axe fighting +2).
> > It can only be wielded properly by knights.
> > Imbuements: (Empty Slot, Empty Slot).
> > It weighs 40.00 oz.
> > 15:21 A leaf loses 559 hitpoints due to your attack.
> > 15:21 A leaf loses 559 hitpoints due to your attack.
> > 15:21 A leaf loses 453 hitpoints due to your attack.
> > 15:21 A leaf loses 501 hitpoints due to your attack.
> > 15:21 A leaf loses 458 hitpoints due to your attack.
> > 15:21 A leaf loses 512 hitpoints due to your attack.
> > 15:21 A leaf loses 678 hitpoints due to your attack.
> > 15:21 A leaf loses 490 hitpoints due to your attack.
> > 15:21 A leaf loses 343 hitpoints due to your attack.
> > 15:21 A leaf loses 755 hitpoints due to your attack.
> > 15:21 A leaf loses 610 hitpoints due to your attack.
> > 15:21 A leaf loses 646 hitpoints due to your attack.
> > 15:21 A leaf loses 708 hitpoints due to your attack.
> > 15:21 A leaf loses 486 hitpoints due to your attack.
> > 15:21 A leaf loses 600 hitpoints due to your attack.
> > 15:21 A leaf loses 471 hitpoints due to your attack.
> > 15:21 A leaf loses 562 hitpoints due to your attack.
> > 15:21 A leaf loses 538 hitpoints due to your attack.
> > 15:21 A leaf loses 491 hitpoints due to your attack.
> > 15:21 A leaf loses 474 hitpoints due to your attack.
> > 15:21 A leaf loses 479 hitpoints due to your attack.
> > 15:21 A leaf loses 448 hitpoints due to your attack.
> > 15:21 A leaf loses 591 hitpoints due to your attack.
> > 15:21 A leaf loses 659 hitpoints due to your attack.
> > 15:21 A leaf loses 320 hitpoints due to your attack.
> > 15:21 A leaf loses 550 hitpoints due to your attack.
> > 15:21 A leaf loses 647 hitpoints due to your attack.
> > 15:21 A leaf loses 468 hitpoints due to your attack.
> > 15:21 A leaf loses 697 hitpoints due to your attack.
> > 15:21 A leaf loses 567 hitpoints due to your attack.
> > 15:21 A leaf loses 754 hitpoints due to your attack.
> > 15:21 A leaf loses 542 hitpoints due to your attack.
> > 15:21 A leaf loses 670 hitpoints due to your attack.
> > Usando Exori gran ~
> > De fato tem um pouco de maior variação com armas elementais.
> > Chegando a ser o dobro de diferença, hits com armas elementais 15:19 A leaf loses 317 hitpoints due to your attack.
> > e hits com 15:19 A leaf loses 730 hitpoints due to your attack. com outra arma.
> 
> Sim, a variação é muito grande...
> Não sei onde bem mexer para ajeitar isso, creio que seja na source o problema

Mas da pra ver que os valores de "pico" estão corretos, o problema de fato é a variação grande

**Comment by Meth28** [comment]
fix:
https://otland.net/threads/tfs-1-3-knight-spells-elemental-weapon-bug-fixx.268328/

**Comment by MajestyOTBR** [comment]
I did the changes: https://github.com/opentibiabr/otservbr-global/commit/470a58d01afc40d25b8b7af0d6a6aee0ebbb3c1e

Anyone to test?

**Comment by Vyruz-web** [comment]
Sim, funciona perfeitamente.
Yes it works.

**Comment by Lycanzito** [comment]
seens fine @MajestyOTBR this one can be closed.

**Comment by majestyotbr** [comment]
Ok.
