### ISSUE TITLE
Black skull cannot attack monsters

### ISSUE THREAD

**Issue by tutbarao** [opentibiabr/otservbr-global#812]
### Priority

Medium

### Area

- [ ] Datapack
- [ ] Source
- [ ] Map
- [X] Other

### What happened?

Black skull is not able to attack monsters.
he should be able

### What OS are you seeing the problem on?

Debian 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by guispiller** [comment]
Black skull players can only attack Skulled players, or attack monsters on single target.
A black skulled player can use single target spells since they are targeted on a monster (for example exori frigo, only with monsters targeted).
The same player can't attack with area spells nor runes, like avalanche.
![image](https://user-images.githubusercontent.com/11639062/200618785-010466da-24bf-46f3-aee9-6b393f1102b9.png)
![image](https://user-images.githubusercontent.com/11639062/200618850-fc4f62b4-8eeb-4eaf-b24c-1f254c22887f.png)

As you can see at the screenshots above, it is possible on canary to attack players single target, with melee weapons or wands/rods, just like it was meant to be.

Closing the issue, as this is not an issue.
